packages:
  - backend
  - frontend
  - shared
  - packages/sri-*
  - apps/*
  - tools/*

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@prisma/client'
  - '@prisma/engines'
  - bcrypt
  - esbuild
  - libxmljs2
  - msgpackr-extract
  - prisma
