export enum VoucherStatus {
  DRAFT = 'DRAFT',
  XML_GENERATED = 'XML_GENERATED',
  SIGNED = 'SIGNED',
  SENT = 'SENT',
  RECEIVED = 'RECEIVED',
  AUTHORIZED = 'AUTHORIZED',
  REJECTED = 'REJECTED',
  ERROR_RETRYABLE = 'ERROR_RETRYABLE',
  ERROR_FINAL = 'ERROR_FINAL',
}
